#!/usr/bin/env bash

# Look for existing vader installation.
vader=( ${HOME}/.vim/*bundle*/vader*/plugin/vader.vim )
if [ -f ${vader[0]} ]; then
    # Remove "plugin/vader.vim" suffix.
    vader=${vader[0]%/*/*}
fi

if [ -d $vader ]; then
    [[ ! -L vader.vim ]] && ln -s $vader
else
    git clone https://github.com/junegunn/vader.vim.git
fi

echo '(Be patient.. testing can take a while.)'
vim -XNu vimrc -i NONE -c 'Vader! *' >/dev/null
