filetype off

set runtimepath+=vader.vim
set runtimepath+=..

filetype plugin on
syntax enable

set hidden
set sessionoptions-=tabpages

let g:startify_session_dir = 'include'
let g:startify_relative_path = 1
let g:startify_custom_header = []
